[default_session]
startup_command = "pwd"

[[session]]
name = "Home ğŸ¡"
path = "$HOME"
startup_command = "yazi"

[[session]]
name = "Code ğŸ’»"
path = "$HOME/Code"
startup_command = "yazi"

[[session]]
name = "Downloads ğŸ“¥"
path = "$HOME/Downloads"
startup_command = "yazi"

[[session]]
name = "Pictures ğŸ“¸"
path = "$HOME/Pictures"
startup_command = "yazi"

[[session]]
name = "Videos ğŸ¥"
path = "$HOME/Movies"
startup_command = "yazi"

[[session]]
name = "Courses ğŸ“š"
path = "/Users/vercent/Res/Course/ZJU/ç ”ç©¶ç”Ÿ/ç ”ç©¶ç”Ÿè¯¾ç¨‹"
startup_command = "ls -al"

[[session]]
name = "Notes ğŸ“"
path = "$HOME/DevNotes"
startup_command = "yazi"

[[session]]
name = "Github"
path = "$HOME/Github"
startup_command = "ls -al"

[[session]]
name = "Dotfiles"
path = "$HOME/Github/dotfiles"
startup_command = "ls -al"

[[session]]
name = "Blog"
path = "$HOME/Github/site/blog"
startup_command = "ls -al"

[[session]]
name = "Notebook"
path = "$HOME/Github/site/notebook"
startup_command = "ls -al"

[[session]]
name = "Workspace ğŸ”­"
path = "$HOME/Github/workspace"
startup_command = "ls -al"

[[session]]
name = "LaTex workspace ğŸ”­"
path = "$HOME/Code/tex"
startup_command = "code tex.code-workspace"

[[session]]
name = "Python workspace ğŸ”­"
path = "$HOME/Code/python"
startup_command = "code python.code-workspace"

[[session]]
name = "C workspace ğŸ”­"
path = "$HOME/Code/c"
startup_command = "code  c.code-workspace"

[[session]]
name = "Cpp workspace ğŸ”­"
path = "$HOME/Code/cpp"
startup_command = "code cpp.code-workspace"

[[session]]
name = "Nvim-config"
path = "$HOME/Github/dotfiles/nvim"
startup_command = "ls -al"

[[session]]
name = "Yazi-config"
path = "$HOME/Github/dotfiles/yazi"
startup_command = "ls -al"

[[session]]
name = "Wezterm-config"
path = "$HOME/Github/dotfiles/wezterm"
startup_command = "ls -al"

[[session]]
name = "Rime-config"
path = "$HOME/Library/Rime"
startup_command = "ls -al"

[[session]]
name = "Zsh-config"
path = "$HOME/Github/dotfiles/zsh"
startup_command = "ls -al"

[[session]]
name = "Tmux-config"
path = "$HOME/Github/dotfiles/tmux"
startup_command = "ls -al"

[[session]]
name = "Sesh-config"
path = "$HOME/Github/dotfiles/sesh"
startup_command = "ls -al"

[[session]]
name = "Alacritty-config"
path = "$HOME/Github/dotfiles/alacritty"
startup_command = "ls -al"

[[session]]
name = "Kitty-config"
path = "$HOME/Github/dotfiles/kitty"
startup_command = "ls -al"

[[session]]
name = "SSH-config"
path = "$HOME/.ssh"
startup_command = "nvim config"
