[default_session]
startup_command = "pwd"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "yazi"

[[session]]
name = "Code ğŸ’»"
path = "~/Code"
startup_command = "yazi"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Pictures ğŸ“¸"
path = "~/Pictures"
startup_command = "yazi"

[[session]]
name = "Videos ğŸ¥"
path = "~/Movies"
startup_command = "yazi"

[[session]]
name = "Courses ğŸ“š"
path = "/Users/vercent/Res/Course/ZJU/ç ”ç©¶ç”Ÿ/ç ”ç©¶ç”Ÿè¯¾ç¨‹"
startup_command = "l"

[[session]]
name = "Notes ğŸ“"
path = "~/DevNotes"
startup_command = "yazi"

[[session]]
name = "Github"
path = "~/Github"
startup_command = "l"

[[session]]
name = "Dotfiles"
path = "~/Github/dotfiles"
startup_command = "l"

[[session]]
name = "Blog"
path = "~/Github/site/blog"
startup_command = "l"

[[session]]
name = "Notebook"
path = "~/Github/site/notebook"
startup_command = "l"

[[session]]
name = "Homepage"
path = "~/Github/site/homepage"
startup_command = "l"

[[session]]
name = "Workspace ğŸ”­"
path = "~/Github/workspace"
startup_command = "l"

[[session]]
name = "LaTex workspace ğŸ”­"
path = "~/Code/tex"
startup_command = "code tex.code-workspace"

[[session]]
name = "Python workspace ğŸ”­"
path = "~/Code/python"
startup_command = "code python.code-workspace"

[[session]]
name = "C workspace ğŸ”­"
path = "~/Code/c"
startup_command = "code  c.code-workspace"

[[session]]
name = "Cpp workspace ğŸ”­"
path = "~/Code/cpp"
startup_command = "code cpp.code-workspace"

[[session]]
name = "Nvim-config"
path = "~/Github/dotfiles/nvim"
startup_command = "l"

[[session]]
name = "Yazi-config"
path = "~/Github/dotfiles/yazi"
startup_command = "l"

[[session]]
name = "Wezterm-config"
path = "~/Github/dotfiles/wezterm"
startup_command = "l"

[[session]]
name = "Rime-config"
path = "~/Library/Rime"
startup_command = "l"

[[session]]
name = "Zsh-config"
path = "~/Github/dotfiles/zsh"
startup_command = "l"

[[session]]
name = "Tmux-config"
path = "~/Github/dotfiles/tmux"
startup_command = "la"

[[session]]
name = "Sesh-config"
path = "~/Github/dotfiles/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Alacritty-config"
path = "~/Github/dotfiles/alacritty"
startup_command = "l"

[[session]]
name = "Kitty-config"
path = "~/Github/dotfiles/kitty"
startup_command = "l"

[[session]]
name = "SSH-config"
path = "~/.ssh"
startup_command = "nvim config"
