[default_session]
startup_command = "pwd"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "yazi"

[[session]]
name = "Code ğŸ’»"
path = "~/Code"
startup_command = "yazi"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Pictures ğŸ“¸"
path = "~/Pictures"
startup_command = "yazi"

[[session]]
name = "Videos ğŸ¥"
path = "~/Movies"
startup_command = "yazi"

[[session]]
name = "Notes ğŸ“"
path = "~/Dev/notes"
startup_command = "yazi"

[[session]]
name = "Workspace ğŸ¢"
path = "~/Github/workspace"
startup_command = "nvim README.md"

[[session]]
name = "Github"
path = "~/Github"
startup_command = "yazi"

[[session]]
name = "Dotfiles"
path = "~/Github/dotfiles"
startup_command = "l"

[[session]]
name = "Blog"
path = "~/Github/site/blog"
startup_command = "l"

[[session]]
name = "Notebook"
path = "~/Github/site/notebook"
startup_command = "l"

[[session]]
name = "LaTex workspace"
path = "~/Code/tex"
startup_command = "code tex.code-workspace"

[[session]]
name = "Python workspace"
path = "~/Code/python"
startup_command = "code python.code-workspace"

[[session]]
name = "C workspace"
path = "~/Code/c"
startup_command = "code c.code-workspace"

[[session]]
name = "Cpp workspace"
path = "~/Code/cpp"
startup_command = "code cpp.code-workspace"

[[session]]
name = "nvim config"
path = "~/Github/dotfiles/nvim"
startup_command = "nvim init.lua"

[[session]]
name = "yazi config"
path = "~/Github/dotfiles/yazi"
startup_command = "nvim init.lua"

[[session]]
name = "rime config"
path = "~/Library/Rime"
startup_command = "nvim squirrel.custom.yaml"

[[session]]
name = "zsh config"
path = "~/Github/dotfiles/zsh"
startup_command = "nvim .zshrc"

[[session]]
name = "tmux config"
path = "~/Github/dotfiles/tmux"
startup_command = "nvim .tmux.conf"

[[session]]
name = "sesh config"
path = "~/Github/dotfiles/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "alacritty config"
path = "~/Github/dotfiles/alacritty"
startup_command = "nvim alacritty.toml"

[[session]]
name = "kitty config"
path = "~/Github/dotfiles/kitty"
startup_command = "nvim kitty.conf"

[[session]]
name = "ssh config"
path = "~/.ssh"
startup_command = "nvim config"
